name: CI Pipeline for the Backend and Frontend

on:
  pull_request:
    types: [opened, review_requested, synchronize]

jobs:
  backend:
    if: "!contains(github.event.pull_request.labels.*.name, 'ops') && !contains(github.head_ref, 'ops/')"
    strategy:
      matrix:
        node: ["22"]
        flavor: ["dev", "prod"]
      fail-fast: false
    runs-on: "ubuntu-latest"
    name: Backend (${{ matrix.flavor }}) - node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ matrix.node }}/${{ matrix.flavor }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"

      - name: Read rust-toolchain file from repository
        id: gettoolchain
        run: echo "toolchain=$(cat ./rust/gbt/rust-toolchain)" >> $GITHUB_OUTPUT
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}

      - name: Install ${{ steps.gettoolchain.outputs.toolchain }} Rust toolchain
        uses: dtolnay/rust-toolchain@315e265cd78dad1e1dcf3a5074f6d6c47029d5aa
        with:
          toolchain: ${{ steps.gettoolchain.outputs.toolchain }}

      - name: Install
        if: ${{ matrix.flavor == 'dev' }}
        run: npm ci
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/backend

      - name: Install (Prod dependencies only)
        if: ${{ matrix.flavor == 'prod' }}
        run: npm ci --omit=dev --omit=optional
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/backend

      - name: Lint
        if: ${{ matrix.flavor == 'dev' }}
        run: npm run lint
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/backend

      - name: Unit Tests
        if: ${{ matrix.flavor == 'dev' }}
        run: npm run test:ci
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/backend

      - name: Build
        run: npm run build
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/backend

  cache:
    name: "Cache assets for builds"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: assets

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install (Prod dependencies only)
        run: npm ci --omit=dev --omit=optional
        working-directory: assets/frontend

      - name: Restore cached mining pool assets
        continue-on-error: true
        id: cache-mining-pool-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            mining-pool-assets.zip
          key: mining-pool-assets-cache

      - name: Restore promo video assets
        continue-on-error: true
        id: cache-promo-video-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            promo-video-assets.zip
          key: promo-video-assets-cache

      - name: Unzip assets before building (mining-pools)
        if: steps.cache-mining-pool-restore.outputs.cache-hit == 'true'
        continue-on-error: true
        run: unzip -o mining-pool-assets.zip -d assets/frontend/src/resources/mining-pools

      - name: Unzip assets before building (promo-video)
        if: steps.cache-promo-video-restore.outputs.cache-hit == 'true'
        continue-on-error: true
        run: unzip -o promo-video-assets.zip -d assets/frontend/src/resources/promo-video

      - name: Sync-assets
        run: npm run sync-assets-dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEMPOOL_CDN: 1
          VERBOSE: 1
        working-directory: assets/frontend

      - name: Zip mining-pool assets
        run: zip -jrq mining-pool-assets.zip assets/frontend/src/resources/mining-pools/*

      - name: Zip promo-video assets
        run: zip -jrq promo-video-assets.zip assets/frontend/src/resources/promo-video/*

      - name: Upload mining pool assets as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mining-pool-assets
          path: mining-pool-assets.zip

      - name: Upload promo video assets as artifact
        uses: actions/upload-artifact@v4
        with:
          name: promo-video-assets
          path: promo-video-assets.zip

      - name: Save mining pool assets cache
        id: cache-mining-pool-save
        uses: actions/cache/save@v4
        with:
          path: |
            mining-pool-assets.zip
          key: mining-pool-assets-cache

      - name: Save promo video assets cache
        id: cache-promo-video-save
        uses: actions/cache/save@v4
        with:
          path: |
            promo-video-assets.zip
          key: promo-video-assets-cache

  frontend:
    needs: cache
    if: "!contains(github.event.pull_request.labels.*.name, 'ops') && !contains(github.head_ref, 'ops/')"
    strategy:
      matrix:
        node: ["22"]
        flavor: ["dev", "prod"]
      fail-fast: false
    runs-on: "ubuntu-latest"
    name: Frontend (${{ matrix.flavor }}) - node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ matrix.node }}/${{ matrix.flavor }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"

      - name: Install (Prod dependencies only)
        if: ${{ matrix.flavor == 'prod' }}
        run: npm ci --omit=dev --omit=optional
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/frontend

      - name: Install
        if: ${{ matrix.flavor == 'dev' }}
        run: npm ci
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/frontend

      - name: Lint
        if: ${{ matrix.flavor == 'dev' }}
        run: npm run lint
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/frontend

      - name: Restore cached mining pool assets
        continue-on-error: true
        id: cache-mining-pool-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            mining-pool-assets.zip
          key: mining-pool-assets-cache

      - name: Restore promo video assets
        continue-on-error: true
        id: cache-promo-video-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            promo-video-assets.zip
          key: promo-video-assets-cache

      - name: Download artifact (mining-pool-assets)
        uses: actions/download-artifact@v4
        with:
          name: mining-pool-assets

      - name: Unzip assets (mining-pools)
        run: unzip -o mining-pool-assets.zip -d ${{ matrix.node }}/${{ matrix.flavor }}/frontend/src/resources/mining-pools

      - name: Download artifact (promo-video-assets)
        uses: actions/download-artifact@v4
        with:
          name: promo-video-assets

      - name: Unzip assets (promo-video)
        run: unzip -o promo-video-assets.zip -d ${{ matrix.node }}/${{ matrix.flavor }}/frontend/src/resources/promo-video

      - name: Display resulting source tree
        run: ls -R

      - name: Build
        run: npm run build
        working-directory: ${{ matrix.node }}/${{ matrix.flavor }}/frontend
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEMPOOL_CDN: 1
          VERBOSE: 1

  e2e-mempool:
    if: "!contains(github.event.pull_request.labels.*.name, 'ops') && !contains(github.head_ref, 'ops/')"
    runs-on: "ubuntu-latest"
    needs: frontend
    name: E2E tests for mempool
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: mempool

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: mempool/frontend/package-lock.json

      - name: Restore cached mining pool assets
        continue-on-error: true
        id: cache-mining-pool-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            mining-pool-assets.zip
          key: mining-pool-assets-cache

      - name: Restore cached promo video assets
        continue-on-error: true
        id: cache-promo-video-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            promo-video-assets.zip
          key: promo-video-assets-cache

      - name: Download artifact (mining-pool-assets)
        uses: actions/download-artifact@v4
        with:
          name: mining-pool-assets
          path: .

      - name: Unzip mining pool assets
        run: unzip -o mining-pool-assets.zip -d mempool/frontend/src/resources/mining-pools

      - name: Download artifact (promo-video-assets)
        uses: actions/download-artifact@v4
        with:
          name: promo-video-assets
          path: .

      - name: Unzip promo video assets
        run: unzip -o promo-video-assets.zip -d mempool/frontend/src/resources/promo-video

      - name: Install dependencies
        run: npm ci
        working-directory: mempool/frontend

      - name: Build configuration
        run: npm run config:defaults:mempool
        working-directory: mempool/frontend

      - name: Start server in background
        run: npm run start:local-staging & && ./node_modules/.bin/wait-on http://localhost:4200
        working-directory: mempool/frontend

      - name: Run Cypress tests
        run: |
          npx cypress run \
            --browser chrome \
            --spec "cypress/e2e/mainnet/*.spec.ts,cypress/e2e/signet/*.spec.ts" \
            ${{ secrets.CYPRESS_RECORD_KEY && '--record --key ' || '' }}${{ secrets.CYPRESS_RECORD_KEY || '' }} \
            --parallel \
            --group "Tests on Chrome (mempool)" \
            --ci-build-id "${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}"
        working-directory: mempool/frontend
        env: 
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

  e2e-liquid:
    if: "!contains(github.event.pull_request.labels.*.name, 'ops') && !contains(github.head_ref, 'ops/')"
    runs-on: "ubuntu-latest"
    needs: frontend
    name: E2E tests for liquid
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: liquid

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: liquid/frontend/package-lock.json

      - name: Restore cached mining pool assets
        continue-on-error: true
        id: cache-mining-pool-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            mining-pool-assets.zip
          key: mining-pool-assets-cache

      - name: Restore cached promo video assets
        continue-on-error: true
        id: cache-promo-video-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            promo-video-assets.zip
          key: promo-video-assets-cache

      - name: Download artifact (mining-pool-assets)
        uses: actions/download-artifact@v4
        with:
          name: mining-pool-assets
          path: .

      - name: Unzip mining pool assets
        run: unzip -o mining-pool-assets.zip -d liquid/frontend/src/resources/mining-pools

      - name: Download artifact (promo-video-assets)
        uses: actions/download-artifact@v4
        with:
          name: promo-video-assets
          path: .

      - name: Unzip promo video assets
        run: unzip -o promo-video-assets.zip -d liquid/frontend/src/resources/promo-video

      - name: Install dependencies
        run: npm ci
        working-directory: liquid/frontend

      - name: Build configuration
        run: npm run config:defaults:liquid
        working-directory: liquid/frontend

      - name: Start server in background
        run: npm run start:local-staging & && ./node_modules/.bin/wait-on http://localhost:4200
        working-directory: liquid/frontend

      - name: Run Cypress tests
        run: |
          npx cypress run \
            --browser chrome \
            --spec "cypress/e2e/liquid/liquid.spec.ts,cypress/e2e/liquidtestnet/liquidtestnet.spec.ts" \
            ${{ secrets.CYPRESS_RECORD_KEY && '--record --key ' || '' }}${{ secrets.CYPRESS_RECORD_KEY || '' }} \
            --parallel \
            --group "Tests on Chrome (liquid)" \
            --ci-build-id "${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}"
        working-directory: liquid/frontend
        env: 
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

  e2e-testnet4:
    if: "!contains(github.event.pull_request.labels.*.name, 'ops') && !contains(github.head_ref, 'ops/')"
    runs-on: "ubuntu-latest"
    needs: frontend
    name: E2E tests for testnet4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: testnet4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: testnet4/frontend/package-lock.json

      - name: Restore cached mining pool assets
        continue-on-error: true
        id: cache-mining-pool-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            mining-pool-assets.zip
          key: mining-pool-assets-cache

      - name: Restore cached promo video assets
        continue-on-error: true
        id: cache-promo-video-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            promo-video-assets.zip
          key: promo-video-assets-cache

      - name: Download artifact (mining-pool-assets)
        uses: actions/download-artifact@v4
        with:
          name: mining-pool-assets
          path: .

      - name: Unzip mining pool assets
        run: unzip -o mining-pool-assets.zip -d testnet4/frontend/src/resources/mining-pools

      - name: Download artifact (promo-video-assets)
        uses: actions/download-artifact@v4
        with:
          name: promo-video-assets
          path: .

      - name: Unzip promo video assets
        run: unzip -o promo-video-assets.zip -d testnet4/frontend/src/resources/promo-video

      - name: Install dependencies
        run: npm ci
        working-directory: testnet4/frontend

      - name: Build configuration
        run: npm run config:defaults:mempool  # testnet4 uses mempool config
        working-directory: testnet4/frontend

      - name: Start server in background
        run: npm run start:local-staging & && ./node_modules/.bin/wait-on http://localhost:4200
        working-directory: testnet4/frontend

      - name: Run Cypress tests
        run: |
          npx cypress run \
            --browser chrome \
            --spec "cypress/e2e/testnet4/*.spec.ts" \
            ${{ secrets.CYPRESS_RECORD_KEY && '--record --key ' || '' }}${{ secrets.CYPRESS_RECORD_KEY || '' }} \
            --parallel \
            --group "Tests on Chrome (testnet4)" \
            --ci-build-id "${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}"
        working-directory: testnet4/frontend
        env: 
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_REROUTE_TESTNET: true

  validate_docker_json:
    if: "!contains(github.event.pull_request.labels.*.name, 'ops') && !contains(github.head_ref, 'ops/')"
    runs-on: "ubuntu-latest"
    name: Validate generated backend Docker JSON
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: docker
      
      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Create new start script to run on CI
        run: |
          sed '$d' start.sh > start_ci.sh
        working-directory: docker/docker/backend

      - name: Run the script to generate the sample JSON
        run: sh start_ci.sh
        working-directory: docker/docker/backend

      - name: Validate JSON syntax
        run: cat mempool-config.json | jq
        working-directory: docker/docker/backend